Allow to show and hide a menu items
libyui/libyui pull request #172
Opened 2020-09-30 07:37 UTC by joseivanlopez

## Problem

A new *YMenuBar* was added to *libyui*, but it lacks of the capability to show/hide items. Although such feature is not used by YaST at all, it is still useful to provide it for some third-party users of the library (i.e., [libyui-mga](https://github.com/manatools/libyui-mga)).

## Solution

Extend public API of *YMenuBar* to allow to indicate whether an item is visible or not. Note that it is possible to hide both: top level menus and also menu items.

See *examples/MenuBar1.cc* to an usage example.

2020-09-30 08:50 UTC, mvidner requested changes
Thanks!
Please add a *.changes entry too

2020-09-30 08:52 UTC, mvidner commented
Please reference the mga issue https://github.com/manatools/libyui-mga/issues/1

2020-09-30 11:41 UTC, joseivanlopez commented
> Thanks!
> Please add a *.changes entry too

The plan is to add a big .changes entry when we are going to merge *sprint-108* into master. Right now, *sprint-108* contains several new features that deserves a comment in the changes file.

2020-09-30 11:59 UTC, joseivanlopez commented
I have added a comment in the mga issue asking for feedback: https://github.com/manatools/libyui-mga/issues/1#issuecomment-701343082.

2020-09-30 12:01 UTC, joseivanlopez commented
> Please reference the mga issue [manatools/libyui-mga#1](https://github.com/manatools/libyui-mga/issues/1)

Commented here https://github.com/manatools/libyui-mga/issues/1#issuecomment-701343082.

2020-10-01 08:44 UTC, mvidner commented
Now I realize that ideally we should have an automated test case, but I am not done making the framework for that just yet :smiley: 

But could you please have a look at https://github.com/yast/yast-ycp-ui-bindings/pull/56 , specifically [this test](https://github.com/yast/yast-ycp-ui-bindings/blob/d761dda3acb0851253de7ccf84c45284933faa08/test/table_sort_wrong_cell_1165388), and check whether `examples/MenuBar1` would work using that approach?

2020-10-01 11:08 UTC, joseivanlopez commented
> Now I realize that ideally we should have an automated test case, but I am not done making the framework for that just yet smiley
> 
> But could you please have a look at [yast/yast-ycp-ui-bindings#56](https://github.com/yast/yast-ycp-ui-bindings/pull/56) , specifically [this test](https://github.com/yast/yast-ycp-ui-bindings/blob/d761dda3acb0851253de7ccf84c45284933faa08/test/table_sort_wrong_cell_1165388), and check whether `examples/MenuBar1` would work using that approach?

Yes, I think we can follow that approach to test *examples/MenuBar1*. Initially, grep should find the menu label, and then, after "clicking" the "Visible" checkbox, the menu should not be found by grep.

2020-10-02 08:44 UTC, mvidner approved these changes

2020-10-02 15:33 UTC, merged